apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-service
  namespace: saas-mesh
spec:
  replicas: 3
  selector:
    matchLabels:
      app: core-service
  template:
    metadata:
      labels:
        app: core-service
    spec:
      containers:
        - name: core
          image: saas/core:latest
          ports:
            - containerPort: 3002
