apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: saas-mesh
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth
          image: saas/auth:latest
          ports:
            - containerPort: 3001
