export const ONBOARDING_STATUS = {
  SIGNED_UP: "SIGNED_UP",
  PROFILE_CREATED: "PROFILE_CREATED",
  ORG_CREATED: "ORG_CREATED",
  MEMBER_ASSIGNED: "MEMBER_ASSIGNED",
  CREDITS_INITIALIZED: "CREDITS_INITIALIZED",
  ACTIVE: "ACTIVE",
} as const;
